name: Hospital API CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Test, Lint and Security
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --no-root --no-interaction

      - name: Run Ruff
        run: poetry run ruff check .

      - name: Run tests with coverage
        run: poetry run pytest --cov=app --cov-report=term-missing --cov-fail-under=85

      - name: Run Bandit
        run: poetry run bandit -r app

  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: ci

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: kushmodi05/hospital-appointment-api:latest